equinix:
  # input_config: { "profile": "equinix", "channel": "2024.1/edge", "channelcp": "edge", "roles": [ "...", "...", "..." ] ] }
  # creds: { "project_id": "xxx", "api_key": "xxx" }
  substrate: equinix
  #api_url: not-used
  sleep_after: 0
  ceph_disks: "/dev/sdb" # space separated list
  manifest:
    deployment:
      region: RegionOne
      proxy:
        proxy_required: False
        http_proxy:
        https_proxy:
        no_proxy:
      #certificates:
      #  <CSR x500UniqueIdentifier>:
      #    certificate:
      bootstrap:
        management_cidr: 10.0.1.0/24
      addons:
        metallb: 10.0.1.20-10.0.1.29
      user:
        remote_access_location: remote
        run_demo_setup: True
        username: demo
        password: password123
        cidr: 192.168.122.0/24
        nameservers: 8.8.8.8
        security_group_rules: True
      external_network:
        cidr: 10.0.2.0/24
        gateway: 10.0.2.1
        start: 10.0.2.11
        end: 10.0.2.254
        network_type: flat
        segmentation_id: 0
        nic: br-ovn # use a bridge to overcome changing if+vlan name
      microceph_config: {} # to be filled by the tool
    software: {}

ob76:
  # input_config: { "profile": "ob76", "channel": "2024.1/edge", "channelcp": "edge", "roles": [ "...", "...", "..." ] }
  # creds: { "api_key": "xxx" }
  substrate: maas
  api_url: "http://ob76-node0.maas:5240/MAAS"
  sleep_after: 5 # boot slow, wait a little before starting deployment
  ceph_disks: "/dev/sdb" # space separated list
  manifest:
    deployment:
      region: RegionOne
      proxy:
        proxy_required: False
        http_proxy:
        https_proxy:
        no_proxy:
      #certificates:
      #  <CSR x500UniqueIdentifier>:
      #    certificate:
      bootstrap:
        management_cidr: 172.27.76.0/23
      addons:
        metallb: 172.27.76.21-172.27.76.30
      user:
        remote_access_location: remote
        run_demo_setup: True
        username: demo
        password: password123
        cidr: 192.168.122.0/24
        nameservers: 172.27.79.254
        security_group_rules: True
      external_network:
        cidr: 172.27.78.0/23
        gateway: 172.27.79.254
        start: 172.27.78.1
        end: 172.27.78.50
        network_type: flat
        segmentation_id: 0
        nic: usb-nic
      microceph_config: {} # to be filled by the tool
    software: {}

ob76deployment:
  # input_config: { "profile": "ob76deployment", "channel": "2024.1/edge", "channelcp": "edge" }
  # creds: { "api_key": "xxx" }
  substrate: maasdeployment
  api_url: "http://ob76-node0.maas:5240/MAAS"
  sleep_after: 5 # boot slow, wait a little before starting deployment
  deployment_name: sunbeamci
  resource_pool: default
  sunbeam_client: sunbeam-client.maas
  destroy_after: True
  spaces_mapping:
    data: oam-space
    internal: oam-space
    management: oam-space
    public: oam-space
    storage: oam-space
    storage-cluster: oam-space
  manifest:
    deployment:
      region: RegionOne
      proxy:
        proxy_required: False
      user:
        remote_access_location: remote
        run_demo_setup: True
        username: demo
        password: password123
        cidr: 192.168.122.0/24
        nameservers: 172.27.79.254
        security_group_rules: True
      external_network:
        cidr: 172.27.78.0/23
        gateway: 172.27.79.254
        start: 172.27.78.1
        end: 172.27.78.50
        network_type: flat
        segmentation_id: 0
    software: {}

felabdeployment:
  # input_config: { "profile": "felabdeployment", "channel": "2024.1/edge", "channelcp": "edge" }
  # creds: { "api_key": "xxx" }
  substrate: maasdeployment
  api_url: "http://172.16.7.10:5240/MAAS/"
  sleep_after: 5 # boot slow, wait a little before starting deployment
  deployment_name: sunbeamci
  resource_pool: sunbeamci
  sunbeam_client: 172.16.7.231
  destroy_after: False
  spaces_mapping:
    data: oam
    internal: oam
    management: oam
    public: oam
    storage: oam
    storage-cluster: oam
  manifest:
    deployment:
      region: RegionOne
      proxy:
        proxy_required: False
      user:
        remote_access_location: remote
        run_demo_setup: True
        username: demo
        password: password123
        cidr: 192.168.122.0/24
        nameservers: 172.27.79.254
        security_group_rules: True
      external_network:
        cidr: 1.0.0.0/24
        gateway: 1.0.0.254
        start: 1.0.0.1
        end: 1.0.0.200
        network_type: flat
        segmentation_id: 0
    software: {}

tokenlabs:
  # input_config: { "profile": "ob76", "channel": "2024.1/edge", "channelcp": "edge", "roles": [ "...", "...", "..." ] }
  # creds: { "api_key": "xxx" }
  substrate: maas
  api_url: "http://microserver.lab.token:5240/MAAS"
  sleep_after: 15 # boot slow, wait for services to settle
  ceph_disks: "/dev/sdb" # space separated list
  manifest:
    deployment:
      region: RegionOne
      proxy:
        proxy_required: False
        http_proxy:
        https_proxy:
        no_proxy:
      #certificates:
      #  <CSR x500UniqueIdentifier>:
      #    certificate:
      bootstrap:
        management_cidr: 192.168.47.0/24
      addons:
        metallb: 192.168.47.30-192.168.47.39
      user:
        remote_access_location: remote
        run_demo_setup: True
        username: demo
        password: password123
        cidr: 192.168.122.0/24
        nameservers: 192.168.47.3
        security_group_rules: True
      external_network:
        cidr: 192.168.50.0/24
        gateway: 192.168.50.1
        start: 192.168.50.11
        end: 192.168.50.254
        network_type: flat
        segmentation_id: 0
        nic: enp2s0.1001
      microceph_config: {} # to be filled by the tool
    software: {}
